spring:
  application:
    name: ${DOMAIN_NAME}
  config:
    import: env.yml
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_ADDRESS}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_DATABASE}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      authentication-database: admin
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
          default_batch_fetch_size: 1000
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
